config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :links, only: %i[new create show]

  get '/:short_url' => 'redirect#show'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/domain.rb
# frozen_string_literal: true

class Domain < ApplicationRecord
  validates :name, presence: true
end

app/models/link.rb
# frozen_string_literal: true

class Link < ApplicationRecord
  before_validation :process_link, on: [:create]

  validates :long_url, :short_url, :salt, presence: true
  validates :short_url, uniqueness: true, length: { is: 6 }

  def process_link
    ProcessLink.new(self).call
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def render404
    render file: "#{Rails.root}/public/404.html", status: 404
  end
end

app/controllers/links_controller.rb
# frozen_string_literal: true

class LinksController < ApplicationController
  def new
    @link = Link.new
  end

  def create
    @link = Link.new(permitted_params)
    if @link.valid?
      @link.save!
      redirect_to link_path(@link.id)
    else
      flash.now[:error] = @link.errors.messages[:long_url].to_sentence
      render :new
    end
  end

  def show
    @link = Link.find(params[:id])
    @short_url = "#{request.base_url}/#{@link.short_url}"
  rescue ActiveRecord::RecordNotFound
    render404
  end

  private

  def permitted_params
    params.require(:link).permit(:long_url)
  end
end

app/controllers/redirect_controller.rb
# frozen_string_literal: true

class RedirectController < ApplicationController
  def show
    link = Link.find_by(short_url: params['short_url'])

    if link.present?
      redirect_to link.long_url
    else
      render404
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/links/new.html.slim
.container-fluid
  .row.justify-content-center
    .col-md-3
      = form_with model: @link, local: true do |form|
        .form_field = form.label :long_url, "Enter url to shorten:"
        .form_field = form.text_field :long_url
        .form_field = form.submit "Create"

      = flash[:error]

app/views/links/show.html.slim
.container-fluid
  .row.justify-content-center
    .col-md-3
      .url = @link.long_url
      a.url href="#{@short_url}" target='_blank'
        = @short_url
      .back = button_to "Back", new_link_path, method: :get